
import java.awt.HeadlessException;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class laporan extends javax.swing.JFrame {
    koneksi k = new koneksi();
    /**
     * Creates new form login
     */
    public laporan() {
        initComponents();
        tampiltabel t = new tampiltabel(tbLaporan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLaporan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        tfNopol = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfJenis = new javax.swing.JTextField();
        masuk = new javax.swing.JLabel();
        tfMasuk = new javax.swing.JTextField();
        btInsert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        tfKeluar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        lJenisPemasukan = new javax.swing.JLabel();
        btMingguan = new javax.swing.JLabel();
        btBulanan = new javax.swing.JLabel();
        btTahunan = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btSearch = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        btHarian = new javax.swing.JLabel();
        bLaporan = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "no parkir", "nopol", "jenis kendaraan", "waktu masuk", "waktu keluar", "lama parkir", "harga parkir"
            }
        ));
        tbLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLaporanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLaporan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, 720, 370));

        jPanel2.setBackground(new java.awt.Color(26, 188, 156));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("nopol");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis");

        masuk.setForeground(new java.awt.Color(255, 255, 255));
        masuk.setText("masuk");

        btInsert.setText("insert");
        btInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertActionPerformed(evt);
            }
        });

        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        btDelete.setText("delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("keluar");

        tfNo.setEditable(false);
        tfNo.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        tfNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("no parkir");

        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Total Pemasukkan ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Rp.");

        lTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lTotal.setText("-");

        lJenisPemasukan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lJenisPemasukan.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lJenisPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lJenisPemasukan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lTotal))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfJenis))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfMasuk))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfKeluar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNo)
                            .addComponent(tfNopol)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btInsert, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNopol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masuk))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 280, 360));

        btMingguan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_layout/bHarian.PNG"))); // NOI18N
        btMingguan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMingguanMouseClicked(evt);
            }
        });
        btMingguan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btMingguanKeyPressed(evt);
            }
        });
        getContentPane().add(btMingguan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 110, 100));

        btBulanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_layout/bBulanan.PNG"))); // NOI18N
        btBulanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBulananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btBulananMouseEntered(evt);
            }
        });
        btBulanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btBulananKeyPressed(evt);
            }
        });
        getContentPane().add(btBulanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 110, 100));

        btTahunan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_layout/bTahunan.PNG"))); // NOI18N
        btTahunan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTahunanMouseClicked(evt);
            }
        });
        btTahunan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btTahunanKeyPressed(evt);
            }
        });
        getContentPane().add(btTahunan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 110, 100));

        tfSearch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfSearch.setText("nopol");
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        getContentPane().add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 140, -1));

        btSearch.setText("search");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        btRefresh.setText("refresh");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        btHarian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_layout/bHarian_1.PNG"))); // NOI18N
        btHarian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHarianMouseClicked(evt);
            }
        });
        getContentPane().add(btHarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 110, 110));

        bLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_layout/Blaporan.PNG"))); // NOI18N
        bLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLaporanMouseClicked(evt);
            }
        });
        getContentPane().add(bLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_layout/bglaporan.jpg"))); // NOI18N
        bg.setText("jLabel3");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLaporanMouseClicked
        int i = tbLaporan.getSelectedRow();
        TableModel model = tbLaporan.getModel();
        tfNo.setText(model.getValueAt(i, 0).toString());
        tfNopol.setText(model.getValueAt(i, 1).toString());
        tfJenis.setText(model.getValueAt(i, 2).toString());
        tfMasuk.setText(model.getValueAt(i, 3).toString());
        tfKeluar.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_tbLaporanMouseClicked

    private void btInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertActionPerformed

        try{
            k.koneksi();
            //Statement cn = (Statement)koneksi.GetConnection().createStatement();
            k.cn.executeUpdate("insert into detail_parkir (nopol,jenis_kendaraan,waktu_masuk,waktu_keluar) values('"+tfNopol.getText()+"','"+tfJenis.getText()+"','"+tfMasuk.getText()+"','"+tfKeluar.getText()+"');");
            ResultSet rs = k.cn.executeQuery("select timestampdiff(hour,waktu_masuk,waktu_keluar) from detail_parkir where nopol='"+tfNopol.getText()+"';");
            String selisih2 = null;
            if(rs.next())
            selisih2 = rs.getString(1);
            int selisih = Integer.valueOf(selisih2);
            int harga = selisih*1000;
            //set lama parkir
            k.cn.executeUpdate("update detail_parkir set lama_parkir="+selisih+" where nopol='"+tfNopol.getText()+"' and waktu_masuk='"+tfMasuk.getText()+"' ;");
            k.cn.executeUpdate("update detail_parkir set harga_parkir="+harga+" where nopol='"+tfNopol.getText()+"' and waktu_masuk='"+tfMasuk.getText()+"';");
            k.conn.close();
            JOptionPane.showMessageDialog(null,"data tersimpan");
        }catch (SQLException | HeadlessException t){
            JOptionPane.showMessageDialog(null,"data tidak tersimpan");
        }
        tampiltabel t = new tampiltabel(tbLaporan);
    }//GEN-LAST:event_btInsertActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try{
            k.koneksi();
            //Statement cn = (Statement)koneksi.GetConnection().createStatement();
            k.cn.executeUpdate("update detail_parkir set nopol='"+tfNopol.getText()+"', jenis_kendaraan='"+tfJenis.getText()+"' , waktu_masuk='"+tfMasuk.getText()+"', waktu_keluar='"+tfKeluar.getText()+"' where id="+tfNo.getText()+";");
            ResultSet rs = k.cn.executeQuery("select timestampdiff(hour,waktu_masuk,waktu_keluar) from detail_parkir where id="+tfNo.getText()+";");
            String selisih2 = null;
            if(rs.next())
                selisih2 = rs.getString(1);
            int selisih = Integer.valueOf(selisih2);
            int harga = selisih*1000;
            //set lama parkir
            k.cn.executeUpdate("update detail_parkir set lama_parkir="+selisih+", harga_parkir="+harga+" where id="+tfNo.getText()+" ;");
            //k.cn.executeUpdate("update detail_parkir set lama_parkir="+selisih+", harga_parkir="+harga+", nopol='"+tfNopol.getText()+"', jenis_kendaraan='"+tfJenis.getText()+"' , waktu_masuk='"+tfMasuk.getText()+"', waktu_keluar='"+tfKeluar.getText()+"' where id="+tfNo.getText()+";");

            JOptionPane.showMessageDialog(null,"data tersimpan");
            k.conn.close();
            tampiltabel t = new tampiltabel(tbLaporan);
        }catch (SQLException | HeadlessException t){
            JOptionPane.showMessageDialog(null,"data tidak tersimpan");
        }

    }//GEN-LAST:event_updateActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        try{
            k.koneksi();
            //Statement cn = (Statement)koneksi.GetConnection().createStatement();
            k.cn.executeUpdate("delete from detail_parkir where id="+tfNo.getText()+";");
            k.conn.close();
            JOptionPane.showMessageDialog(null,"data tersimpan");
            tampiltabel t = new tampiltabel(tbLaporan);
        }catch (SQLException | HeadlessException t){
            JOptionPane.showMessageDialog(null,"data tidak tersimpan");
        }

    }//GEN-LAST:event_btDeleteActionPerformed

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed

        tampiltabel t = new tampiltabel(tbLaporan, tfSearch.getText());
    }//GEN-LAST:event_btSearchActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        tampiltabel t = new tampiltabel(tbLaporan);
    }//GEN-LAST:event_btRefreshActionPerformed

    private void tfNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoActionPerformed

    private void btMingguanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btMingguanKeyPressed
        
    }//GEN-LAST:event_btMingguanKeyPressed

    private void btBulananKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btBulananKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBulananKeyPressed

    private void btBulananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBulananMouseClicked
        tampilReport();
        //untuk print
        Map<String,Object> param = new HashMap<String,Object>();
        try {
            String reportSource = System.getProperty("user.dir")+"\\src\\laporan\\laporan2.jrxml";
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            Connection c = k.conn;
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param,c);
            JasperViewer.viewReport(jasperPrint,false);
        } catch (Exception e) {
            System.out.println(e);
        } 
        
        //menghitung pemasukan total
        ResultSet rs;
        try {
            rs = k.cn.executeQuery("select sum(harga_parkir) from detail_parkir WHERE " +
"waktu_masuk between date(DATE_SUB(NOW(), INTERVAL 30 day)) and date (now());");
            String total = null;
            if(rs.next())
                total = rs.getString(1);
            lTotal.setText(total);
            lJenisPemasukan.setText("Bulanan :");
            
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        tampiltabel t = new tampiltabel(tbLaporan, 30);
        
    }                                        

    private void pLapHarianMouseClicked(java.awt.event.MouseEvent evt) {                                        
        tampilReport();
        //untuk print
        Map<String,Object> param = new HashMap<String,Object>();
        try {
            String reportSource = System.getProperty("user.dir")+"\\src\\laporan\\laporan1.jrxml";
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            Connection c = k.conn;
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param,c);
            JasperViewer.viewReport(jasperPrint,false);
        } catch (Exception e) {
            System.out.println(e);
        } 
        
        //menghitung pemasukan total
        ResultSet rs;
        try {
            rs = k.cn.executeQuery("select sum(harga_parkir) from detail_parkir WHERE " +
"waktu_masuk between date(DATE_SUB(NOW(), INTERVAL 1 day)) and date (now());");
            String total = null;
            if(rs.next())
                total = rs.getString(1);
            lTotal.setText(total);
            lJenisPemasukan.setText("Harian :");
            
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        tampiltabel t = new tampiltabel(tbLaporan, 1);
    }//GEN-LAST:event_btBulananMouseClicked

    private void btTahunanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btTahunanKeyPressed
        
    }                                        

    private void pLapBulananMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        tampilReport();
        //untuk print
        Map<String,Object> param = new HashMap<String,Object>();
        try {
            String reportSource = System.getProperty("user.dir")+"\\src\\laporan\\laporan2.jrxml";
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            Connection c = k.conn;
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param,c);
            JasperViewer.viewReport(jasperPrint,false);
        } catch (Exception e) {
            System.out.println(e);
        } 
        
        //menghitung pemasukan total
        ResultSet rs;
        try {
            rs = k.cn.executeQuery("select sum(harga_parkir) from detail_parkir WHERE " +
"waktu_masuk between date(DATE_SUB(NOW(), INTERVAL 30 day)) and date (now());");
            String total = null;
            if(rs.next())
                total = rs.getString(1);
            lTotal.setText(total);
            lJenisPemasukan.setText("Bulanan :");
            
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        tampiltabel t = new tampiltabel(tbLaporan, 30);
    }//GEN-LAST:event_btTahunanKeyPressed

    private void btMingguanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMingguanMouseClicked
        tampilReport();
        //untuk print
        Map<String,Object> param = new HashMap<String,Object>();
        try {
            String reportSource = System.getProperty("user.dir")+"\\src\\laporan\\laporan1.jrxml";
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            Connection c = k.conn;
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param,c);
            JasperViewer.viewReport(jasperPrint,false);
        } catch (Exception e) {
            System.out.println(e);
        } 
        
        //menghitung pemasukan total
        ResultSet rs;
        try {
            rs = k.cn.executeQuery("select sum(harga_parkir) from detail_parkir WHERE " +
"waktu_masuk between date(DATE_SUB(NOW(), INTERVAL 7 day)) and date (now());");
            String total = null;
            if(rs.next())
                total = rs.getString(1);
            lTotal.setText(total);
            lJenisPemasukan.setText("Mingguan :");
            
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        tampiltabel t = new tampiltabel(tbLaporan, 7);
    }//GEN-LAST:event_btMingguanMouseClicked

    private void btTahunanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTahunanMouseClicked
        tampilReport();
        //untuk print
        
        Map<String,Object> param = new HashMap<String,Object>();
        try {
            String reportSource = System.getProperty("user.dir")+"\\src\\laporan\\laporan3.jrxml";
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            Connection c = k.conn;
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param,c);
            JasperViewer.viewReport(jasperPrint,false);
        } catch (Exception e) {
            System.out.println(e);
        } 
        
        //menghitung pemasukan total
        ResultSet rs;
        try {
            rs = k.cn.executeQuery("select sum(harga_parkir) from detail_parkir WHERE " +
"waktu_masuk between date(DATE_SUB(NOW(), INTERVAL 365 day)) and date (now());");
            String total = null;
            if(rs.next())
                total = rs.getString(1);
            lTotal.setText(total);
            lJenisPemasukan.setText("Tahunan :");
            
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        tampiltabel t = new tampiltabel(tbLaporan, 365);
    }//GEN-LAST:event_btTahunanMouseClicked

    private void btBulananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBulananMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btBulananMouseEntered

    private void btHarianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHarianMouseClicked
        tampilReport();
        //tampiltabel t = new tampiltabel(tbLaporan);
        //untuk print
        
        
        Map<String,Object> param = new HashMap<String,Object>();
        try {
            String reportSource = System.getProperty("user.dir")+"\\src\\laporan\\laporan4.jrxml";
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            Connection c = k.conn;
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, param,c);
            JasperViewer.viewReport(jasperPrint,false);
        } catch (Exception e) {
            System.out.println(e);
        } 
 
        
        
        //menghitung pemasukan total
        ResultSet rs;
        try {
            rs = k.cn.executeQuery("select sum(harga_parkir) from detail_parkir WHERE " +
"waktu_masuk between date(DATE_SUB(NOW(), INTERVAL 1 day)) and date (now());");
            String total = null;
            if(rs.next())
                total = rs.getString(1);
            lTotal.setText(total);
            lJenisPemasukan.setText("Harian :");
            
        } catch (SQLException ex) {
            Logger.getLogger(laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btHarianMouseClicked

    private void bLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLaporanMouseClicked
        this.setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_bLaporanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }
    
    public void tampilReport(){
        String field[]={"nomor parkir","nomor polisi","jenis kendaraan","waktu masuk","waktu keluar","lama parkir(jam)","harga parkir (Rp)"};
        DefaultTableModel tblLaporan = new DefaultTableModel(null,field);
        try{ 
            k.koneksi();
            String sql = "select * from detail_parkir";
            ResultSet rs = k.cn.executeQuery(sql);
            while (rs.next())
            {
                tblLaporan.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                });
            }
            tbLaporan.setModel(tblLaporan);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ada kesalahan");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bLaporan;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btBulanan;
    private javax.swing.JButton btDelete;
    private javax.swing.JLabel btHarian;
    private javax.swing.JButton btInsert;
    private javax.swing.JLabel btMingguan;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btSearch;
    private javax.swing.JLabel btTahunan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lJenisPemasukan;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel masuk;
    private javax.swing.JTable tbLaporan;
    private javax.swing.JTextField tfJenis;
    private javax.swing.JTextField tfKeluar;
    private javax.swing.JTextField tfMasuk;
    private javax.swing.JTextField tfNo;
    private javax.swing.JTextField tfNopol;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
