import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.imageio.ImageIO;
import javax.swing.Icon;
public class ParkirKeluar extends javax.swing.JFrame {
    koneksi k = new koneksi();
    /**
     * Creates new form login
     */
    public ParkirKeluar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCari = new javax.swing.JTextField();
        lHarga = new javax.swing.JLabel();
        bCari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfCariNopol = new javax.swing.JTextField();
        buatFoto = new javax.swing.JPanel();
        Foto = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_layout/Bkeluar.PNG"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 250, 120));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("atau Nomor Polisi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        tfCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariActionPerformed(evt);
            }
        });
        jPanel1.add(tfCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 240, 30));

        lHarga.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lHarga.setForeground(new java.awt.Color(255, 255, 255));
        lHarga.setText("Rp.");
        jPanel1.add(lHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 250, -1));

        bCari.setText("cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });
        jPanel1.add(bCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 80, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nomor Parkir");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, 30));
        jPanel1.add(tfCariNopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 280, 370));

        buatFoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        buatFoto.add(Foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 360, 360));

        getContentPane().add(buatFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 360, 370));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_layout/menubg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariActionPerformed
    public Image scaledImage(Image img, int w, int h){
        BufferedImage resizedImage = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, w, h, null);
        g2.dispose();
        return resizedImage;
    }
    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        // TODO add your handling code here:
        String cari = tfCari.getText();
        String cariNopol = tfCariNopol.getText();
        String tanggalSekarang = getTanggal();
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("C:\\Users\\DELL\\Desktop\\"+cari+".png"));
        } catch (IOException ex) {
            Logger.getLogger(ParkirKeluar.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image ii = scaledImage(img, Foto.getWidth(), Foto.getHeight());
        ImageIcon imi = new ImageIcon(ii);
        Foto.setIcon(imi);
        try{
            k.koneksi();
            //Statement cn = (Statement)koneksi.GetConnection().createStatement();
            k.cn.executeUpdate("update detail_parkir set waktu_keluar='"+tanggalSekarang+"' where id="+cari+" and nopol='"+cariNopol+"';");
            //k.cn.executeQuery("select timestampdiff(hour,waktu_masuk,waktu_keluar) from detail_parkir where id="+cari+";");
            //ResultSet rs = k.cn.executeQuery("select * from detail_parkir;");
            ResultSet rs = k.cn.executeQuery("select timestampdiff(hour,waktu_masuk,waktu_keluar) from detail_parkir where id="+cari+" and nopol='"+cariNopol+"';");

            String selisih2 = null;
            if(rs.next()){
                selisih2 = rs.getString(1);
            }               
            int selisih = Integer.valueOf(selisih2);
            if (selisih==0){
                selisih = 1;
            }
            
            //set lama parkir
            k.cn.executeUpdate("update detail_parkir set lama_parkir="+selisih+" where id="+cari+" and nopol='"+cariNopol+"';");
            //set harga
            ResultSet rss = k.cn.executeQuery("select jenis_kendaraan from detail_parkir where id="+cari+" and nopol='"+cariNopol+"';");
            String jenis = null;
            if(rss.next()){
                jenis = rss.getString(1);
            }                
            ResultSet rsss = k.cn.executeQuery("select tarif from tarifkendaraan where kendaraan='"+jenis+"';");
            String tarif2 = null;
            if(rsss.next()){
                tarif2 = rsss.getString(1);
            }                
            int tarif = Integer.valueOf(tarif2);
            
            
            int harga = selisih*tarif;
            k.cn.executeUpdate("update detail_parkir set harga_parkir="+harga+" where id="+cari+" and nopol='"+cariNopol+"';");
            lHarga.setText("Rp."+harga);

            //int selisih = Integer.valueOf(?);
            k.conn.close();
            JOptionPane.showMessageDialog(null,"data tersimpan");

        }
        catch (SQLException | HeadlessException t){
            JOptionPane.showMessageDialog(null,"data tidak tersimpan");
        }

    }//GEN-LAST:event_bCariActionPerformed

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2KeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkirKeluar().setVisible(true);
            }
        });
    }
    
    public String getTanggal(){
        Date date = new Date();
        DateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String dateNow = String.format(dateFormat.format(date));
        return dateNow;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Foto;
    private javax.swing.JButton bCari;
    private javax.swing.JLabel bg;
    private javax.swing.JPanel buatFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lHarga;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfCariNopol;
    // End of variables declaration//GEN-END:variables
}
