import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TambahAdmin extends javax.swing.JFrame {
    koneksi k = new koneksi();
    /**
     * Creates new form TambahAdmin
     */
    public TambahAdmin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        rTambahAdmin = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 195, 30));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 195, 30));

        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 143, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 181, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Nama Lengkap");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 219, -1, -1));

        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 80, -1));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 195, 30));

        rTambahAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_layout/rTambahAdmin.PNG"))); // NOI18N
        rTambahAdmin.setText("jLabel4");
        rTambahAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rTambahAdminMouseClicked(evt);
            }
        });
        getContentPane().add(rTambahAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 100, 100));

        jenis.setForeground(new java.awt.Color(255, 0, 0));
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "operator" }));
        getContentPane().add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_layout/bgTambahAdmin.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 375, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        k.koneksi();
        try {
            k.cn.executeUpdate("INSERT INTO admin(username, password, nama, Jenis_Pegawai) VALUES ('"+user.getText()+"', '"+pass.getText()+"', '"+name.getText()+"', '"+jenis.getSelectedItem().toString()+"');");
            JOptionPane.showMessageDialog(null,"data sudah dimasukkan");
        } catch (SQLException ex) {
            Logger.getLogger(TambahAdmin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"username sudah ada");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        
    }//GEN-LAST:event_userActionPerformed

    private void rTambahAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rTambahAdminMouseClicked
        this.setVisible(false);
        new Admin().setVisible(true);
    }//GEN-LAST:event_rTambahAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel rTambahAdmin;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
